<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends EntityRepository {
    
    public function findByName($userId, $name) {
        return $this->createQueryBuilder('p')
                ->where("p.name ='" . $name . "'")
                ->andWhere("p.user =" .$userId)
                ->getQuery()
                ->execute();
    }
    
    public function findSingleResultByName($userId, $name) {
        return $this->createQueryBuilder('p')
                ->where("p.name ='" . $name . "'")
                ->andWhere("p.user =" .$userId)
                ->getQuery()
                ->setMaxResults(1)
                ->getOneOrNullResult();
    }
    
    public function autocomplete($userId, $name){
        return $this->createQueryBuilder('p')        
                ->where('p.name LIKE :name')
                ->setParameter('name', '%' . $name . '%')
                ->andWhere("p.user =" .$userId)
                ->getQuery()
                ->getResult();
    }
}
