<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends EntityRepository {
    
    public function findByName($userId, $name) {
        return $this->createQueryBuilder('p')
                ->where("p.name ='" . $name . "'")
                ->andWhere("p.user =" .$userId)
                ->getQuery()
                ->execute();
    }
}
