<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GliderRepository extends EntityRepository
{
    public function getGliderByUserId($userId) {
        $res = $this->createQueryBuilder('g')
                ->where('g.user =' . $userId)
                ->getQuery()
                ->getResult();
        return $res;
    }
}
